add_cross_attention: false
anyres: false
architectures:
- Qwen2_5_VisionTransformerPretrainedModel
bad_words_ids: null
begin_suppress_tokens: null
bos_token_id: null
chunk_size_feed_forward: 0
cross_attention_hidden_size: null
decoder_start_token_id: null
depth: 32
diversity_penalty: 0.0
do_sample: false
dtype: bfloat16
early_stopping: false
encoder_no_repeat_ngram_size: 0
eos_token_id: null
exponential_decay_length_penalty: null
finetuning_task: null
forced_bos_token_id: null
forced_eos_token_id: null
fullatt_block_indexes:
- 7
- 15
- 23
- 31
hidden_act: silu
hidden_size: 1280
id2label:
  0: LABEL_0
  1: LABEL_1
in_channels: 3
in_chans: 3
initializer_range: 0.02
intermediate_size: 3456
is_decoder: false
is_encoder_decoder: false
label2id:
  LABEL_0: 0
  LABEL_1: 1
length_penalty: 1.0
max_length: 20
max_num_grids: -1
min_length: 0
model_type: qwen2_5_vl
no_repeat_ngram_size: 0
num_beam_groups: 1
num_beams: 1
num_heads: 16
num_return_sequences: 1
out_hidden_size: 5120
output_attentions: false
output_hidden_states: false
output_scores: false
pad_token_id: null
patch_size: 14
prefix: null
problem_type: null
pruned_heads: {}
remove_invalid_values: false
repetition_penalty: 1.0
return_dict: true
return_dict_in_generate: false
sep_token_id: null
spatial_merge_size: 2
spatial_patch_size: 14
suppress_tokens: null
task_specific_params: null
temperature: 1.0
temporal_patch_size: 2
tf_legacy_loss: false
tie_encoder_decoder: false
tie_word_embeddings: true
tokenizer_class: null
tokens_per_second: 2
top_k: 50
top_p: 1.0
torchscript: false
transformers_version: 4.56.1
typical_p: 1.0
use_bfloat16: true
window_size: 112
